org: findsweeddie 

service:
  name: sls-bugtracker-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin
  - serverless-plugin-tracing 

package:
  exclude:
    - .dynamodb/**
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  
  tracing: 
    lambda: true
    apiGateway: true
    iamRoleStatements:
    - Effect: 'Allow' 
      Action: 
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment: 
    BUGS_TABLE: bugs-${self:provider.stage}
    S3_BUCKET: bugtracker-s3-bucket-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    AUTH_0_SECRET: sw1kz_dPufhXOIj4pnq-TdNaHc-fC_7U9y2VjtWf-h_N6K0v7Yx_T0r-AY6NCEw4
    S3_BUCKET_URL: https://${self:provider.environment.S3_BUCKET}.s3.amazonaws.com/
    UPLOAD_TOPIC_ARN: 
      fn::Join:
        - ':'
        - - arn:aws:sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${self:custom.topicName}

# Custom Configuration
custom: 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
  topicName: UploadTopic-${self:provider.stage}
  documentation:
    api:
      info:
        version: v1.1.0
        title: Bug Tracker API
        description: Serverless Bug Tracker Application
    models:
      - name: CreateBug
        contentType: application/json
        schema: ${file(src/models/createBugModel.json)}
      - name: UpdateBug
        contentType: application/json
        schema: ${file(src/models/updateBugModel.json)}
functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # GetBugs: lambda function to get all BUG items
  GetBugs:
    handler: src/lambda/http/getBugs.handler
    events:
      - http:
          method: get
          path: bugs
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}
      - Effect: Allow
        Action:
          - cloudformation:DescribeStackResource
        Resource: "*"
      - Effect: "Allow"
        Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
        Resource: "*"

  # CreateBug: lambda function to create Bug items
  CreateBug:
    handler: src/lambda/http/createBug.handler
    events:
      - http:
          method: post
          path: bugs
          cors: true
          reqValidatorName: RequestValidator
          documentation:
            summary: add new bug
            description: add new bug
            requestModels:
              'application/json': CreateBug
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}
      - Effect: "Allow"
        Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
        Resource: "*"

  # UpdateBug: lambda function to update a BUG
  UpdateBug:
    handler: src/lambda/http/updateBug.handler
    events:
      - http:
          method: patch
          path: bugs/{bugId}
          cors: true
          reqValidatorName: RequestValidator
          documentation:
            summary: update bug
            description: update bug
            requestModels:
              'application/json': UpdateBug
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}

  # DeleteBug: lambda function to delete a BUG
  DeleteBug:
    handler: src/lambda/http/deleteBug.handler
    events:
      - http:
          method: delete
          path: bugs/{bugId}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}

  # GenerateUploadUrl: lambda function to generate the image upload url
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          authorizer: Auth
          method: post
          path: bugs/{bugId}/attachment
          cors: true 
          origin: '*'    
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.BUGS_TABLE}
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - '*'
        Resource: 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'  
      - Effect: "Allow" # xray permissions 
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'DELETE,GET,OPTIONS,POST,PUT,PATCH'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    RequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false  


    BugsDyanmoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: bugId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: bugId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.BUGS_TABLE} 
    
    # Necessary AWS bucket permissions and policies
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopicPolicy
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:PutItem
              Topic: !Ref UploadTopic 
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 10000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadWriteBucketPolicy
              Effect: Allow
              Principal: '*'
              Action: 
                - s3:GetObject
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'
        Bucket: !Ref AttachmentsBucket
    
    SNSTopicPolicy: 
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow 
              Principal: 
                AWS: "*"
              Action: sns:Publish
              Resource: 
                !Ref UploadTopic
              Condition: 
                ArnLike: 
                  AWS:SourceArn: arn:aws:s3:::${self:provider.environment.S3_BUCKET}
        Topics: 
          - !Ref UploadTopic

    UploadTopic: 
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: Upload bucket topic
        TopicName: ${self:custom.topicName}